# Generated by Django 5.1.5 on 2025-01-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('txt2json_input_file', models.CharField(blank=True, default='', max_length=255)),
                ('txt2json_output_dir', models.CharField(blank=True, default='', max_length=255)),
                ('md2tei_input_file', models.CharField(blank=True, default='', max_length=255)),
                ('md2tei_output_file', models.CharField(blank=True, default='', max_length=255)),
                ('tei2json_input_file', models.CharField(blank=True, default='', max_length=255)),
                ('tei2json_output_dir', models.CharField(blank=True, default='', max_length=255)),
                ('combine_collations_input_dir', models.CharField(blank=True, default='', max_length=255)),
                ('combine_collations_output_file', models.CharField(blank=True, default='', max_length=255)),
                ('combine_collations_startswith', models.CharField(blank=True, default='', max_length=255)),
                ('combine_collations_title_stmt', models.CharField(blank=True, default='', max_length=255)),
                ('combine_collations_publication_stmt', models.CharField(blank=True, default='', max_length=255)),
                ('reformat_collation_input_file', models.CharField(blank=True, default='', max_length=255)),
                ('reformat_collation_output_file', models.CharField(blank=True, default='', max_length=255)),
                ('reformat_collation_title_stmt', models.CharField(blank=True, default='', max_length=255)),
                ('reformat_collation_publication_stmt', models.CharField(blank=True, default='', max_length=255)),
                ('tei_viewer_input_dir', models.CharField(blank=True, default='', max_length=255)),
                ('collation_editor_config_file', models.CharField(blank=True, default='', max_length=255)),
                ('export_collation_input_file', models.CharField(blank=True, default='', max_length=255)),
                ('export_collation_output_file', models.CharField(blank=True, default='', max_length=255)),
                ('export_collation_use_custom_template', models.BooleanField(default=False)),
                ('export_collation_custom_template', models.CharField(blank=True, default='', max_length=255)),
                ('export_collation_text_wits_separator', models.CharField(blank=True, default=' // ', max_length=255)),
                ('export_collation_id_text_separator', models.CharField(blank=True, default='', max_length=255)),
                ('export_collation_wits_separator', models.CharField(blank=True, default='', max_length=255)),
                ('export_collation_basetext_words_per_line', models.IntegerField(default=10)),
                ('export_collation_rdg_bold', models.BooleanField(default=True)),
                ('export_collation_collapse_regularized', models.BooleanField(default=False)),
                ('export_collation_add_suffix_to_child', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='CustomRegex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('expression', models.CharField(max_length=255)),
                ('replacement', models.CharField(max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tei2json_regexes', to='web.settings')),
            ],
            options={
                'verbose_name_plural': 'Custom Regexes',
            },
        ),
    ]
